apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: m3project
          image: axelsilverdew/complex_api
          resources: 
             limits:
                 memory: "128Mi"
                 cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service-cluster
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: simple_blog_api
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD